import { useState } from 'react'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import { checkExpiry } from '../utils.js'

function getStatusForReq(req, fileId, expiryDate, deadline) {
  if (!fileId) return req.mandatory ? 'missing' : 'optional_missing'
  if (req.has_expiry) return checkExpiry(expiryDate || '', deadline)
  return 'ok'
}

async function buildCoverPage(pdfDoc, tender, reqStatuses) {
  const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const fontReg = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const page = pdfDoc.addPage([595, 842]) // A4

  const { width, height } = page.getSize()
  const margin = 50

  // Header background
  page.drawRectangle({
    x: 0,
    y: height - 120,
    width,
    height: 120,
    color: rgb(0.12, 0.33, 0.6),
  })

  // Title
  page.drawText('TENDER PACKAGE', {
    x: margin,
    y: height - 55,
    size: 26,
    font,
    color: rgb(1, 1, 1),
  })
  page.drawText('Document Submission Package', {
    x: margin,
    y: height - 78,
    size: 12,
    font: fontReg,
    color: rgb(0.75, 0.87, 1),
  })

  // Draw a line
  const drawLine = (y) => {
    page.drawLine({
      start: { x: margin, y },
      end: { x: width - margin, y },
      thickness: 1,
      color: rgb(0.85, 0.88, 0.93),
    })
  }

  // Tender details
  let y = height - 160
  const details = [
    ['Tender ID', tender.tender_id],
    ['Tender Title', tender.tender_title],
    ['Procuring Entity', tender.procuring_entity],
    ['Bidder', tender.bidder],
    ['Submission Deadline', tender.submission_deadline],
    ['Generated At', new Date().toISOString().split('T')[0]],
  ]

  for (const [label, value] of details) {
    page.drawText(label + ':', {
      x: margin,
      y,
      size: 9,
      font,
      color: rgb(0.45, 0.5, 0.58),
    })
    page.drawText(String(value), {
      x: margin + 130,
      y,
      size: 10,
      font: fontReg,
      color: rgb(0.15, 0.15, 0.2),
      maxWidth: width - margin - 130 - margin,
    })
    y -= 20
  }

  y -= 10
  drawLine(y)
  y -= 30

  // Table header
  page.drawText('DOCUMENT CHECKLIST', {
    x: margin,
    y,
    size: 11,
    font,
    color: rgb(0.12, 0.33, 0.6),
  })
  y -= 20

  // Column headers
  const colX = [margin, margin + 30, margin + 200, margin + 310, margin + 410]
  const headers = ['#', 'Document', 'File', 'Expiry', 'Status']
  for (let i = 0; i < headers.length; i++) {
    page.drawText(headers[i], {
      x: colX[i],
      y,
      size: 8,
      font,
      color: rgb(0.4, 0.45, 0.5),
    })
  }
  y -= 4
  drawLine(y)
  y -= 12

  // Rows
  for (const { req, file, status, expiryDate } of reqStatuses) {
    if (y < 60) break // Safety

    const statusColor = {
      ok: rgb(0.1, 0.55, 0.2),
      expired: rgb(0.7, 0.1, 0.1),
      needed: rgb(0.75, 0.45, 0.0),
      missing: rgb(0.7, 0.1, 0.1),
      optional_missing: rgb(0.6, 0.6, 0.6),
    }[status] || rgb(0.4, 0.4, 0.4)

    const statusLabel = {
      ok: 'OK',
      expired: 'EXPIRED',
      needed: 'DATE NEEDED',
      missing: 'MISSING',
      optional_missing: 'NOT PROVIDED',
    }[status] || status.toUpperCase()

    page.drawText(String(req.order), { x: colX[0], y, size: 8, font: fontReg, color: rgb(0.5, 0.5, 0.5) })

    // Title — truncate if too long
    const titleText = req.title_en.length > 25 ? req.title_en.slice(0, 22) + '…' : req.title_en
    page.drawText(titleText, { x: colX[1], y, size: 8, font: fontReg, color: rgb(0.2, 0.2, 0.25) })

    const fileName = file ? (file.name.length > 18 ? file.name.slice(0, 15) + '…' : file.name) : '—'
    page.drawText(fileName, { x: colX[2], y, size: 8, font: fontReg, color: rgb(0.3, 0.3, 0.35) })

    const expiryText = req.has_expiry && expiryDate ? expiryDate : (req.has_expiry ? '—' : 'N/A')
    page.drawText(expiryText, { x: colX[3], y, size: 8, font: fontReg, color: rgb(0.4, 0.4, 0.4) })

    page.drawText(statusLabel, { x: colX[4], y, size: 8, font, color: statusColor })

    y -= 16
    if (y > 60) {
      page.drawLine({
        start: { x: margin, y: y + 4 },
        end: { x: width - margin, y: y + 4 },
        thickness: 0.3,
        color: rgb(0.9, 0.9, 0.92),
      })
    }
  }

  // Footer
  page.drawText('Generated by Tender Package Builder', {
    x: margin,
    y: 30,
    size: 8,
    font: fontReg,
    color: rgb(0.65, 0.68, 0.72),
  })
  page.drawText(`Total pages: calculating…`, {
    x: width - margin - 100,
    y: 30,
    size: 8,
    font: fontReg,
    color: rgb(0.65, 0.68, 0.72),
  })
}

export default function GeneratePackage({ tender, uploadedFiles, matches, expiryDates }) {
  const [generating, setGenerating] = useState(false)
  const [progress, setProgress] = useState('')
  const [error, setError] = useState(null)
  const [downloadUrl, setDownloadUrl] = useState(null)
  const [downloadName, setDownloadName] = useState('')

  const fileMap = Object.fromEntries(uploadedFiles.map(f => [f.id, f]))

  const reqStatuses = tender.requirements.map(req => {
    const fileId = matches[req.id]
    const file = fileId ? fileMap[fileId] : null
    const expiryDate = expiryDates[req.id] || ''
    const status = getStatusForReq(req, fileId, expiryDate, tender.submission_deadline)
    return { req, file, status, expiryDate }
  })

  const missingMandatory = reqStatuses.filter(r => r.status === 'missing').length
  const expiredCount = reqStatuses.filter(r => r.status === 'expired').length
  const expiryNeeded = reqStatuses.filter(r => r.status === 'needed').length
  const isReadyToGenerate = missingMandatory === 0 && expiredCount === 0 && expiryNeeded === 0

  const generate = async () => {
    setGenerating(true)
    setError(null)
    setDownloadUrl(null)

    try {
      setProgress('Creating PDF package…')
      const mergedPdf = await PDFDocument.create()

      // Build cover page
      setProgress('Building cover page…')
      await buildCoverPage(mergedPdf, tender, reqStatuses)

      // Merge matched files in order
      const matchedReqs = reqStatuses.filter(r => r.file)
      let processed = 0

      for (const { req, file } of matchedReqs) {
        setProgress(`Adding "${req.title_en}" (${++processed}/${matchedReqs.length})…`)
        try {
          const arrayBuffer = await file.file.arrayBuffer()
          const srcPdf = await PDFDocument.load(arrayBuffer, { ignoreEncryption: true })
          const pages = await mergedPdf.copyPages(srcPdf, srcPdf.getPageIndices())
          pages.forEach(p => mergedPdf.addPage(p))
        } catch (err) {
          throw new Error(`Failed to merge "${file.name}": ${err.message}`)
        }
      }

      setProgress('Finalizing PDF…')
      mergedPdf.setTitle(`Tender Package - ${tender.tender_id}`)
      mergedPdf.setAuthor(tender.bidder)
      mergedPdf.setSubject(tender.tender_title)
      mergedPdf.setCreator('Tender Package Builder')
      mergedPdf.setCreationDate(new Date())

      const pdfBytes = await mergedPdf.save()
      const blob = new Blob([pdfBytes], { type: 'application/pdf' })
      const url = URL.createObjectURL(blob)

      const safeName = `tender-package-${tender.tender_id.replace(/[^a-zA-Z0-9_-]/g, '_')}-${new Date().toISOString().slice(0, 10)}.pdf`

      setDownloadUrl(url)
      setDownloadName(safeName)
      setProgress(`Done! Package ready (${(pdfBytes.length / 1024 / 1024).toFixed(2)} MB, ${mergedPdf.getPageCount()} pages)`)
    } catch (err) {
      setError(err.message)
      setProgress('')
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
      <h2 className="text-lg font-bold text-gray-800 mb-4 flex items-center gap-2">
        <svg className="w-5 h-5 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
            d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        Generate & Download Package
      </h2>

      {!isReadyToGenerate && (
        <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-sm text-red-700 space-y-1">
          <p className="font-medium">Cannot generate — please resolve the following issues first:</p>
          {missingMandatory > 0 && <p>• {missingMandatory} mandatory document(s) have no file assigned</p>}
          {expiredCount > 0 && <p>• {expiredCount} document(s) have expired by the submission deadline</p>}
          {expiryNeeded > 0 && <p>• {expiryNeeded} document(s) require an expiry date</p>}
        </div>
      )}

      {/* Package summary */}
      <div className="mb-5 p-4 bg-gray-50 rounded-xl border border-gray-200 text-sm">
        <p className="font-semibold text-gray-700 mb-2">What will be included in the package:</p>
        <ol className="space-y-1.5">
          <li className="flex items-start gap-2">
            <span className="bg-blue-600 text-white text-xs font-bold w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">C</span>
            <span className="text-gray-700">Cover Page (auto-generated with checklist)</span>
          </li>
          {reqStatuses.filter(r => r.file).map(({ req, file }, i) => (
            <li key={req.id} className="flex items-start gap-2">
              <span className="bg-gray-200 text-gray-600 text-xs font-bold w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">{i + 1}</span>
              <span className="text-gray-700">
                <span className="font-medium">{req.title_en}</span>
                <span className="text-gray-400 ml-2 text-xs">← {file.name}</span>
              </span>
            </li>
          ))}
        </ol>
        {reqStatuses.filter(r => r.file).length === 0 && (
          <p className="text-gray-400 italic text-sm">No files matched yet.</p>
        )}
      </div>

      {/* Action button */}
      <div className="flex flex-col sm:flex-row gap-3 items-start">
        <button
          onClick={generate}
          disabled={generating || !isReadyToGenerate}
          className={`
            flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm transition-all
            ${isReadyToGenerate && !generating
              ? 'bg-blue-600 hover:bg-blue-700 text-white shadow-md hover:shadow-lg'
              : 'bg-gray-200 text-gray-400 cursor-not-allowed'
            }
          `}
        >
          {generating ? (
            <>
              <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              Generating…
            </>
          ) : (
            <>
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Generate PDF Package
            </>
          )}
        </button>

        {downloadUrl && (
          <a
            href={downloadUrl}
            download={downloadName}
            className="flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm bg-green-600 hover:bg-green-700 text-white shadow-md hover:shadow-lg transition-all"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download {downloadName}
          </a>
        )}
      </div>

      {/* Progress / status */}
      {progress && (
        <div className={`mt-4 p-3 rounded-xl text-sm flex items-center gap-2 ${downloadUrl ? 'bg-green-50 border border-green-200 text-green-700' : 'bg-blue-50 border border-blue-200 text-blue-700'}`}>
          {generating ? (
            <svg className="w-4 h-4 animate-spin flex-shrink-0" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
          ) : (
            <svg className="w-4 h-4 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
            </svg>
          )}
          {progress}
        </div>
      )}

      {error && (
        <div className="mt-4 p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm flex gap-2">
          <svg className="w-5 h-5 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
          </svg>
          <div>
            <p className="font-semibold">Generation failed</p>
            <p>{error}</p>
          </div>
        </div>
      )}
    </div>
  )
}
